import type { Entity, Rating } from "@/lib/types";

const now = new Date().toISOString();

export const sampleEntities: Entity[] = [
  {
    id: "ent-bashkia-tirane",
    name: "Bashkia Tiranë",
    slug: "bashkia-tirane-tirane",
    type: "municipality",
    description:
      "Institucion vendor për shërbime publike, dokumente dhe komunikim me qytetarët.",
    ai_description:
      "Bashkia Tiranë është institucion vendor që ofron shërbime për qytetarët e Tiranës. Vlerësimet fokusohen te transparenca, pritja dhe zgjidhja e problemeve.",
    address: "Sheshi Skënderbej",
    city: "Tiranë",
    country: "Albania",
    lat: 41.3275,
    lng: 19.8189,
    claim_status: "unclaimed",
    status: "active",
    average_score: 3.1,
    weighted_score: 3.3,
    total_ratings: 128,
    recommend_percent: 46,
    return_percent: 41,
    trust_index: 77,
    trend_delta: 0.2,
    recent_reviews_count: 18,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ent-spitali-universitar-tirane",
    name: "Spitali Universitar Tiranë",
    slug: "spitali-universitar-tirane-tirane",
    type: "hospital",
    description:
      "Qendër spitalore universitare me shërbime publike mjekësore.",
    ai_description:
      "Përdoruesit vlerësojnë profesionalizmin, kohën e pritjes, komunikimin dhe cilësinë e kujdesit.",
    address: "Rruga e Dibrës",
    city: "Tiranë",
    country: "Albania",
    lat: 41.3408,
    lng: 19.8339,
    claim_status: "pending",
    status: "active",
    average_score: 2.7,
    weighted_score: 2.8,
    total_ratings: 143,
    recommend_percent: 31,
    return_percent: 22,
    trust_index: 81,
    trend_delta: 0.4,
    recent_reviews_count: 24,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ent-bkt-dega-tirane",
    name: "BKT Dega Tiranë",
    slug: "bkt-dega-tirane-tirane",
    type: "bank",
    description: "Degë bankare për shërbime klientësh dhe transaksione.",
    ai_description:
      "Vlerësimet matin kohën në radhë, sjelljen e stafit, transparencën e tarifave dhe shërbimet online.",
    address: "Bulevardi Zogu I",
    city: "Tiranë",
    country: "Albania",
    lat: 41.333,
    lng: 19.817,
    claim_status: "approved",
    status: "active",
    average_score: 4.1,
    weighted_score: 4.3,
    total_ratings: 56,
    recommend_percent: 78,
    return_percent: 73,
    trust_index: 86,
    trend_delta: 0.1,
    recent_reviews_count: 9,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ent-vodafone-albania",
    name: "Vodafone Albania",
    slug: "vodafone-albania-tirane",
    type: "internet_provider",
    description: "Operator telekomunikacioni dhe interneti në Shqipëri.",
    ai_description:
      "Përdoruesit raportojnë eksperiencën me shpejtësinë, korrektësinë, suportin dhe transparencën e faturimit.",
    address: "Rruga Ibrahim Rugova",
    city: "Tiranë",
    country: "Albania",
    lat: 41.3219,
    lng: 19.8162,
    claim_status: "unclaimed",
    status: "active",
    average_score: 3.4,
    weighted_score: 3.2,
    total_ratings: 92,
    recommend_percent: 49,
    return_percent: 45,
    trust_index: 75,
    trend_delta: -0.3,
    recent_reviews_count: 21,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ent-one-albania",
    name: "One Albania",
    slug: "one-albania-tirane",
    type: "internet_provider",
    description: "Operator telefoni, interneti dhe shërbimesh digjitale.",
    ai_description:
      "Vlerësimet përqendrohen te mbulimi, zgjidhja e problemeve dhe qartësia e paketave.",
    address: "Rruga Murat Toptani",
    city: "Tiranë",
    country: "Albania",
    lat: 41.326,
    lng: 19.821,
    claim_status: "unclaimed",
    status: "active",
    average_score: 2.9,
    weighted_score: 2.6,
    total_ratings: 74,
    recommend_percent: 36,
    return_percent: 29,
    trust_index: 72,
    trend_delta: -0.5,
    recent_reviews_count: 26,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ent-oda-shkoder",
    name: "Oda Shkodrane",
    slug: "oda-shkodrane-shkoder",
    type: "restaurant",
    description: "Restorant tradicional në Shkodër.",
    ai_description:
      "Klientët vlerësojnë ushqimin, atmosferën, shërbimin dhe drejtësinë e çmimeve.",
    address: "Rruga Kolë Idromeno",
    city: "Shkodër",
    country: "Albania",
    lat: 42.068,
    lng: 19.512,
    claim_status: "unclaimed",
    status: "active",
    average_score: 4.5,
    weighted_score: 4.6,
    total_ratings: 38,
    recommend_percent: 91,
    return_percent: 88,
    trust_index: 89,
    trend_delta: 0.6,
    recent_reviews_count: 12,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ent-shkolla-ismet-qemali",
    name: "Shkolla Ismail Qemali",
    slug: "shkolla-ismail-qemali-vlore",
    type: "school",
    description: "Shkollë publike në Vlorë.",
    ai_description:
      "Prindërit dhe nxënësit vlerësojnë mësimin, sigurinë, komunikimin dhe ambientet.",
    address: "Rruga Kosova",
    city: "Vlorë",
    country: "Albania",
    lat: 40.466,
    lng: 19.49,
    claim_status: "unclaimed",
    status: "active",
    average_score: 3.8,
    weighted_score: 3.9,
    total_ratings: 22,
    recommend_percent: 64,
    return_percent: 59,
    trust_index: 83,
    trend_delta: 0.1,
    recent_reviews_count: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "ent-zyra-tatimeve-durres",
    name: "Drejtoria e Tatimeve Durrës",
    slug: "drejtoria-e-tatimeve-durres-durres",
    type: "government_office",
    description: "Zyrë rajonale për shërbime tatimore.",
    ai_description:
      "Qytetarët vlerësojnë transparencën, kohën e pritjes dhe zgjidhjen e çështjeve.",
    address: "Lagjja 1",
    city: "Durrës",
    country: "Albania",
    lat: 41.318,
    lng: 19.444,
    claim_status: "unclaimed",
    status: "active",
    average_score: 2.3,
    weighted_score: 2.1,
    total_ratings: 35,
    recommend_percent: 19,
    return_percent: 17,
    trust_index: 79,
    trend_delta: -0.4,
    recent_reviews_count: 11,
    created_at: now,
    updated_at: now,
  },
];

export const sampleRatings: Rating[] = [
  {
    id: "rat-1",
    entity_id: "ent-spitali-universitar-tirane",
    user_id: "sample-user-1",
    device_id: "sample-device-1",
    overall: 3,
    service: 2,
    trust: 3,
    cleanliness: 3,
    speed: 2,
    fairness: 3,
    would_recommend: false,
    would_return: false,
    comment:
      "Mjekët në urgjencë ishin korrektë, por pritja ishte shumë e gjatë dhe komunikimi mund të jetë më i qartë.",
    gps_verified: true,
    gps_lat: 41.3407,
    gps_lng: 19.8338,
    gps_accuracy_meters: 18,
    distance_meters: 24,
    weight: 2.1,
    fraud_score: 4,
    status: "approved",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rat-2",
    entity_id: "ent-bkt-dega-tirane",
    user_id: "sample-user-2",
    device_id: "sample-device-2",
    overall: 5,
    service: 5,
    trust: 4,
    cleanliness: 5,
    speed: 4,
    fairness: 4,
    would_recommend: true,
    would_return: true,
    comment:
      "Shërbim i shpejtë dhe staf i qartë. Radha u menaxhua mirë gjatë mëngjesit.",
    gps_verified: true,
    gps_lat: 41.333,
    gps_lng: 19.817,
    gps_accuracy_meters: 12,
    distance_meters: 8,
    weight: 2.25,
    fraud_score: 2,
    status: "approved",
    created_at: now,
    updated_at: now,
  },
  {
    id: "rat-3",
    entity_id: "ent-zyra-tatimeve-durres",
    user_id: "sample-user-3",
    device_id: "sample-device-3",
    overall: 2,
    service: 2,
    trust: 2,
    cleanliness: 3,
    speed: 1,
    fairness: 2,
    would_recommend: false,
    would_return: false,
    comment:
      "Pritja ishte e gjatë dhe udhëzimet nuk ishin të njëjta nga sporteli në sportel.",
    gps_verified: true,
    gps_lat: 41.318,
    gps_lng: 19.444,
    gps_accuracy_meters: 22,
    distance_meters: 18,
    weight: 2,
    fraud_score: 5,
    status: "approved",
    created_at: now,
    updated_at: now,
  },
];
